"use client";

import { useState, useEffect } from "react";
import { FaPlus, FaFileExcel, FaMagic, FaList, FaCheckSquare } from "react-icons/fa";

export default function TabScope({ data, onUpdate }: { data?: any, onUpdate?: (updates: any) => void }) {
    const [viewMode, setViewMode] = useState<"structured" | "sow">("structured");
    const [uomOptions, setUomOptions] = useState<any[]>([]);
    const [uploadingIndex, setUploadingIndex] = useState<number | null>(null);
    const [isGenerating, setIsGenerating] = useState(false);
    const [deliverables, setDeliverables] = useState<{ text: string, checked: boolean }[]>([]);

    useEffect(() => {
        const fetchUoms = async () => {
            try {
                const res = await fetch("/api/administration/fields/uom");
                if (res.ok) {
                    const data = await res.json();
                    setUomOptions(data);
                }
            } catch (error) {
                console.error("Failed to fetch UOMs", error);
            }
        };
        fetchUoms();
    }, []);

    // Also populate deliverables from props if available
    useEffect(() => {
        if (data?.deliverables && Array.isArray(data.deliverables)) {
            // Handle migration from string[] to object[]
            const parsed = data.deliverables.map((d: any) => {
                if (typeof d === "string") return { text: d, checked: false };
                return d;
            });
            setDeliverables(parsed);
        }
    }, [data?.deliverables]);

    const handleAddLine = () => {
        const newItem = {
            title: "",
            quantity: 0,
            uom: "Each",
            location: "",
            attachment: "",
        };
        const newItems = [...(data?.items || []), newItem];
        onUpdate?.({ items: newItems });
    };

    const handleUpdateItem = (index: number, field: string, value: any) => {
        const newItems = [...(data?.items || [])];
        newItems[index] = { ...newItems[index], [field]: value };
        onUpdate?.({ items: newItems });
    };

    const handleRemoveItem = (index: number) => {
        const newItems = [...(data?.items || [])];
        newItems.splice(index, 1);
        onUpdate?.({ items: newItems });
    };

    const handleFileUpload = async (index: number, files: FileList | null) => {
        if (!files || files.length === 0) return;

        setUploadingIndex(index);
        const file = files[0];

        try {
            let contentType = file.type || "application/octet-stream";
            // Get presigned URL
            const presignRes = await fetch("/api/uploads/presign", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ filename: file.name, contentType }),
            });

            if (!presignRes.ok) throw new Error("Failed to get presigned URL");

            const { url, fields: s3Fields, publicUrl } = await presignRes.json();

            // Upload to S3
            const formData = new FormData();
            Object.entries(s3Fields).forEach(([k, v]) => formData.append(k, String(v)));
            formData.append("Content-Type", contentType);
            formData.append("file", file);

            const uploadRes = await fetch(url, { method: "POST", body: formData });
            if (!uploadRes.ok) throw new Error("S3 Upload Failed");

            // Update item with public URL
            handleUpdateItem(index, "attachment", publicUrl);

        } catch (error) {
            console.error("Upload failed", error);
            alert("Upload failed. Please try again.");
        } finally {
            setUploadingIndex(null);
        }
    };

    const handleAutoGenerateDeliverables = async () => {
        if (!data?.sowSummary) {
            alert("Please provide a Scope of Work summary first.");
            return;
        }

        setIsGenerating(true);
        try {
            const res = await fetch("/api/ai/generate-deliverables", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ sowSummary: data.sowSummary }),
            });

            if (!res.ok) throw new Error("Failed to generate details");

            const { deliverables: newStrings } = await res.json();
            if (Array.isArray(newStrings)) {
                // Convert strings to objects
                const newDeliverables = newStrings.map((s: string) => ({ text: s, checked: false }));
                setDeliverables(newDeliverables);
                onUpdate?.({ deliverables: newDeliverables });
            }
        } catch (error) {
            console.error("AI Generation Error", error);
            alert("Failed to generate deliverables.");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleAutoGenerateItems = async () => {
        if (!data?.sowSummary) {
            alert("Please provide a Scope of Work summary first.");
            return;
        }

        setIsGenerating(true);
        try {
            const res = await fetch("/api/ai/generate-items", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ sowSummary: data.sowSummary }),
            });

            if (!res.ok) throw new Error("Failed to generate items");

            const { items: newGeneratedItems } = await res.json();
            if (Array.isArray(newGeneratedItems)) {
                const currentItems = data?.items || [];
                const mergedItems = [...currentItems, ...newGeneratedItems];
                onUpdate?.({ items: mergedItems });
            }
        } catch (error) {
            console.error("AI Generation Error", error);
            alert("Failed to generate items.");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleAddDeliverable = () => {
        const updated = [...deliverables, { text: "", checked: false }];
        setDeliverables(updated);
        onUpdate?.({ deliverables: updated });
    };

    const handleUpdateDeliverableProp = (index: number, field: "text" | "checked", val: any) => {
        const updated = [...deliverables];
        updated[index] = { ...updated[index], [field]: val };
        setDeliverables(updated);
        onUpdate?.({ deliverables: updated });
    };

    const handleRemoveDeliverable = (index: number) => {
        const updated = deliverables.filter((_, i) => i !== index);
        setDeliverables(updated);
        onUpdate?.({ deliverables: updated });
    };

    const [isRewriting, setIsRewriting] = useState(false);

    const handleRewriteSow = async () => {
        if (!data?.sowSummary) {
            alert("Please enter some text to rewrite.");
            return;
        }

        setIsRewriting(true);
        try {
            const res = await fetch("/api/ai/rewrite-sow", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ text: data.sowSummary }),
            });

            if (!res.ok) throw new Error("Failed to rewrite");

            const { rewrittenText } = await res.json();
            if (rewrittenText) {
                onUpdate?.({ sowSummary: rewrittenText });
            }
        } catch (error) {
            console.error("Rewrite failed", error);
            alert("Failed to rewrite text.");
        } finally {
            setIsRewriting(false);
        }
    };

    return (
        <div className="space-y-6">
            {/* Toggle */}
            <div className="bg-white p-2 rounded-lg inline-flex border border-gray-200 shadow-sm">
                <button
                    onClick={() => setViewMode("structured")}
                    className={`px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2 ${viewMode === "structured" ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50"
                        }`}
                >
                    <FaList /> Structured Items
                </button>
                <button
                    onClick={() => setViewMode("sow")}
                    className={`px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2 ${viewMode === "sow" ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50"
                        }`}
                >
                    <FaCheckSquare /> Scope of Work
                </button>
            </div>

            {viewMode === "structured" && (
                <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
                    {/* Toolbar */}
                    <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center bg-gray-50">
                        <h3 className="font-semibold text-gray-800">Line Items</h3>
                        <div className="flex gap-2">
                            <button className="flex items-center gap-2 text-sm px-3 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 text-gray-700 font-medium transition">
                                <FaImportExcel className="text-green-600" /> Import Excel
                            </button>
                            <button
                                onClick={handleAutoGenerateItems}
                                disabled={isGenerating}
                                className="flex items-center gap-2 text-sm px-3 py-2 bg-purple-50 border border-purple-100 rounded-lg hover:bg-purple-100 text-purple-700 font-medium transition disabled:opacity-50"
                            >
                                <FaMagic /> {isGenerating ? "Generating..." : "AI Generate"}
                            </button>
                            <button
                                onClick={handleAddLine}
                                className="flex items-center gap-2 text-sm px-3 py-2 bg-blue-600 rounded-lg hover:bg-blue-700 text-white font-medium transition"
                            >
                                <FaPlus /> Add Line
                            </button>
                        </div>
                    </div>

                    {/* Table */}
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-gray-100 text-gray-600 font-medium">
                                <tr>
                                    <th className="px-6 py-3">Description</th>
                                    <th className="px-6 py-3 w-32">Quantity</th>
                                    <th className="px-6 py-3 w-32">UoM</th>
                                    <th className="px-6 py-3">Delivery Location</th>
                                    <th className="px-6 py-3 w-40">Attachment</th>
                                    <th className="px-6 py-3 w-20">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-200">
                                {data?.items?.length > 0 ? (
                                    data.items.map((item: any, i: number) => (
                                        <tr key={i} className="hover:bg-blue-50/50 transition-colors">
                                            <td className="px-6 py-3">
                                                <input
                                                    type="text"
                                                    className="w-full bg-transparent border-none focus:ring-0 p-0"
                                                    placeholder="Item description..."
                                                    value={item.title || item.description || ""}
                                                    onChange={(e) => handleUpdateItem(i, "title", e.target.value)}
                                                />
                                            </td>
                                            <td className="px-6 py-3">
                                                <input
                                                    type="number"
                                                    className="w-full bg-transparent border-none focus:ring-0 p-0"
                                                    placeholder="0"
                                                    value={item.quantity || 0}
                                                    onChange={(e) => handleUpdateItem(i, "quantity", e.target.value)}
                                                />
                                            </td>
                                            <td className="px-6 py-3">
                                                <select
                                                    className="w-full bg-transparent border-none focus:ring-0 p-0"
                                                    value={item.uom || "Each"}
                                                    onChange={(e) => handleUpdateItem(i, "uom", e.target.value)}
                                                >
                                                    <option value="Each">Each</option>
                                                    {uomOptions.map((opt: any) => (
                                                        <option key={opt.id} value={opt.name}>{opt.name}</option>
                                                    ))}
                                                </select>
                                            </td>
                                            <td className="px-6 py-3">
                                                <input
                                                    type="text"
                                                    className="w-full bg-transparent border-none focus:ring-0 p-0"
                                                    placeholder="Location..."
                                                    value={item.location || ""}
                                                    onChange={(e) => handleUpdateItem(i, "location", e.target.value)}
                                                />
                                            </td>
                                            <td className="px-6 py-3">
                                                {item.attachment ? (
                                                    <div className="flex items-center gap-2">
                                                        <a href={item.attachment} target="_blank" rel="noreferrer" className="text-blue-600 hover:underline truncate max-w-[100px] block">
                                                            View File
                                                        </a>
                                                        <button onClick={() => handleUpdateItem(i, "attachment", "")} className="text-red-400 hover:text-red-600">
                                                            <FaTimes />
                                                        </button>
                                                    </div>
                                                ) : (
                                                    <div className="relative">
                                                        <input
                                                            type="file"
                                                            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                                                            onChange={(e) => handleFileUpload(i, e.target.files)}
                                                            disabled={uploadingIndex === i}
                                                        />
                                                        <button className={`text-xs px-2 py-1 rounded border ${uploadingIndex === i ? "bg-gray-100 text-gray-400" : "bg-white border-gray-300 text-gray-600 hover:bg-gray-50"}`}>
                                                            {uploadingIndex === i ? "Uploading..." : "Upload"}
                                                        </button>
                                                    </div>
                                                )}
                                            </td>
                                            <td className="px-6 py-3">
                                                <button
                                                    onClick={() => handleRemoveItem(i)}
                                                    className="text-red-400 hover:text-red-600"
                                                >
                                                    <FaTimes />
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                ) : (
                                    <tr>
                                        <td colSpan={6} className="px-6 py-4 text-center text-gray-500">No items added. Add a line or import from Excel.</td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    </div>

                    <div className="px-6 py-3 border-t border-gray-200 bg-gray-50 text-xs text-gray-500 text-center">
                        Showing {data?.items?.length || 0} items
                    </div>
                </div>
            )}

            {viewMode === "sow" && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    <div className="lg:col-span-2 space-y-6">
                        {/* SOW Summary */}
                        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                            <div className="flex justify-between items-center mb-4">
                                <h3 className="font-semibold text-gray-800">SOW Summary</h3>
                                <button
                                    onClick={handleRewriteSow}
                                    disabled={isRewriting}
                                    className="text-xs text-purple-600 flex items-center gap-1 font-medium hover:underline disabled:opacity-50"
                                >
                                    <FaMagic /> {isRewriting ? "Rewriting..." : "Rewrite for Clarity"}
                                </button>
                            </div>
                            <textarea
                                className="w-full h-32 p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
                                placeholder="Describe the scope of work in detail..."
                                value={data?.sowSummary || ""}
                                onChange={(e) => onUpdate?.({ sowSummary: e.target.value })}
                            />
                        </div>

                        {/* Deliverables */}
                        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                            <div className="flex justify-between items-center mb-4">
                                <h3 className="font-semibold text-gray-800">Deliverables</h3>
                                <button
                                    onClick={handleAutoGenerateDeliverables}
                                    disabled={isGenerating}
                                    className="text-xs text-purple-600 flex items-center gap-1 font-medium hover:underline disabled:opacity-50"
                                >
                                    <FaMagic /> {isGenerating ? "Generating..." : "Auto-Generate"}
                                </button>
                            </div>
                            <div className="space-y-3">
                                {deliverables.length > 0 ? deliverables.map((item, i) => (
                                    <div key={i} className="flex items-center gap-3 group">
                                        <input
                                            type="checkbox"
                                            className="rounded text-blue-600 focus:ring-blue-500 border-gray-300"
                                            checked={!!item.checked}
                                            onChange={(e) => handleUpdateDeliverableProp(i, "checked", e.target.checked)}
                                        />
                                        <input
                                            type="text"
                                            className="flex-1 border-b border-transparent focus:border-gray-300 focus:ring-0 bg-transparent text-sm p-1 group-hover:bg-gray-50 rounded"
                                            placeholder="Deliverable description..."
                                            value={item.text || ""}
                                            onChange={(e) => handleUpdateDeliverableProp(i, "text", e.target.value)}
                                        />
                                        <button
                                            onClick={() => handleRemoveDeliverable(i)}
                                            className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500 transition-opacity"
                                        >
                                            <FaTimes />
                                        </button>
                                    </div>
                                )) : (
                                    <div className="text-sm text-gray-400 italic">No deliverables yet. Add one or generate using AI.</div>
                                )}
                                <button
                                    onClick={handleAddDeliverable}
                                    className="text-sm text-blue-600 font-medium hover:underline flex items-center gap-1 mt-2"
                                >
                                    <FaPlus /> Add Deliverable
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* Sidebar hidden as per request */}
                    {/* <div className="space-y-6">
                        <div className="bg-purple-50 border border-purple-100 rounded-xl p-5">
                            <h4 className="font-semibold text-purple-900 mb-3 flex items-center gap-2"><FaMagic /> AI Actions</h4>
                            <div className="space-y-2">
                                <button className="w-full text-left bg-white p-3 rounded-lg text-sm text-purple-800 shadow-sm border border-purple-100 hover:bg-purple-50 transition">Convert to Structured Items</button>
                                <button className="w-full text-left bg-white p-3 rounded-lg text-sm text-purple-800 shadow-sm border border-purple-100 hover:bg-purple-50 transition">Draft SLA Terms</button>
                            </div>
                        </div>

                        <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
                            <h4 className="font-semibold text-gray-800 mb-3">Timeline</h4>
                            <div className="space-y-4 relative pl-4 border-l-2 border-gray-200">
                                {["Kickoff", "Development", "UAT", "Go-Live"].map((step, idx) => (
                                    <div key={idx} className="relative">
                                        <div className="absolute -left-[21px] top-1 w-3 h-3 rounded-full bg-blue-500 border-2 border-white ring-1 ring-gray-200"></div>
                                        <div className="text-sm font-medium text-gray-900">{step}</div>
                                        <div className="text-xs text-gray-500">Dec {10 + idx * 5}</div>
                                    </div>
                                ))}
                                <button className="text-xs text-blue-600 font-medium hover:underline mt-2">+ Add Milestone</button>
                            </div>
                        </div>
                    </div> */}
                </div>
            )}
        </div>
    );
}

// Helper component for icon
function FaImportExcel({ className }: { className?: string }) {
    return <FaFileExcel className={className} />;
}
function FaTimes() {
    return <span className="text-lg">×</span>
}
