import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header"
import { Toaster } from "@/components/ui/sonner";
import Provider from "./components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Provider>
          <Header />
          <div className="mt-16"></div>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
