"use client";

import { useEffect, useState } from "react";

interface Deliverable {
  title: string;
  description: string;
  userInstruction: string;
  // internal flags to avoid duplicate generation
  generating?: boolean;
  generated?: boolean;
}

interface SlideScopeOfWorkProps {
  procurementDraft: any;
  setProcurementDraft: (draft: any) => void;
  next: () => void;
  prev: () => void;
}

export default function SlideScopeOfWork({
  procurementDraft,
  setProcurementDraft,
  next,
  prev,
}: SlideScopeOfWorkProps) {
  // Helper to get a sensible initial title from draft
  const initialTitleFromDraft = () =>
    procurementDraft?.title?.toString().trim() ||
    procurementDraft?.description?.toString().trim() ||
    "";

  const initialDeliverables = procurementDraft?.scopeOfWork && procurementDraft.scopeOfWork.length
    ? procurementDraft.scopeOfWork
    : [{ title: initialTitleFromDraft(), description: "", userInstruction: "" }];

  const [deliverables, setDeliverables] = useState<Deliverable[]>(initialDeliverables);

  // Keep component state in sync if parent draft changes (e.g. bot populates description/title)
  useEffect(() => {
    const title = initialTitleFromDraft();
    const newDeliverables =
      procurementDraft?.scopeOfWork && procurementDraft.scopeOfWork.length
        ? procurementDraft.scopeOfWork
        : [{ title, description: "", userInstruction: "" }];

    setDeliverables(newDeliverables);
    // Ensure parent draft is updated if it didn't already have scopeOfWork
    if ((!procurementDraft?.scopeOfWork || procurementDraft.scopeOfWork.length === 0) && title) {
      setProcurementDraft({ ...procurementDraft, scopeOfWork: newDeliverables });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [procurementDraft?.title, procurementDraft?.description, procurementDraft?.scopeOfWork]);

  // Persist helper
  const persistAndUpdateParent = (updatedDeliverables: Deliverable[]) => {
    setDeliverables(updatedDeliverables);
    setProcurementDraft({ ...procurementDraft, scopeOfWork: updatedDeliverables });
  };

  const addDeliverable = () => {
    const updated = [...deliverables, { title: "", description: "", userInstruction: "" }];
    persistAndUpdateParent(updated);
  };

  const updateDeliverable = (index: number, key: keyof Deliverable, value: string) => {
    const updated = deliverables.map((d, i) => (i === index ? { ...d, [key]: value } : d));
    persistAndUpdateParent(updated);
  };

  // Auto-generate description from title:
  const autoGenerateDescriptionForIndex = async (index: number) => {
    const d = deliverables[index];
    if (!d?.title || d.description?.trim() || d.generating || d.generated) return;

    // mark generating
    const markGenerating = deliverables.map((item, i) =>
      i === index ? { ...item, generating: true } : item
    );
    persistAndUpdateParent(markGenerating);

    try {
      const res = await fetch("/api/ai/sow", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // send title as description and provide a clear instruction to expand
        body: JSON.stringify({
          description: d.title,
          instruction: `Expand the title into a clear deliverable description. Keep it concise, 2-4 sentences, and action-oriented.`,
        }),
      });

      if (!res.ok) {
        console.error("AI SOW error:", await res.text());
        // unset generating so we can retry later (or user can press Improve with AI)
        const unset = deliverables.map((item, i) =>
          i === index ? { ...item, generating: false } : item
        );
        persistAndUpdateParent(unset);
        return;
      }

      const data = await res.json();
      const addition = data.addition || data.description || ""; // be flexible with API shape
      const newDescription = addition.trim() || `Deliverable: ${d.title}`;

      const updated = deliverables.map((item, i) =>
        i === index
          ? { ...item, description: newDescription, generating: false, generated: true }
          : item
      );

      persistAndUpdateParent(updated);
    } catch (err) {
      console.error("Auto-generate failed:", err);
      const unset = deliverables.map((item, i) =>
        i === index ? { ...item, generating: false } : item
      );
      persistAndUpdateParent(unset);
    }
  };

  // Watch for deliverables that need auto-generation (title present, description empty)
  useEffect(() => {
    deliverables.forEach((d, idx) => {
      if (d.title?.trim() && !d.description?.trim() && !d.generating && !d.generated) {
        // fire-and-forget (we await inside the function)
        autoGenerateDescriptionForIndex(idx);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [deliverables.map((d) => d.title + "|" + d.description + "|" + !!d.generating + "|" + !!d.generated).join(";;")]);

  const handleGenerate = async (index: number) => {
    // existing "Improve with AI" functionality - use the userInstruction if present,
    // otherwise fall back to the title as instruction.
    const deliverable = deliverables[index];
    if (!deliverable.userInstruction.trim() && !deliverable.title.trim()) {
      alert("Please enter an instruction or a title to improve the description.");
      return;
    }

    // If user provided an instruction, prefer that; else use the title as the seed
    const instruction = deliverable.userInstruction.trim()
      ? deliverable.userInstruction
      : `Expand the title into a more detailed deliverable description. Title: "${deliverable.title}"`;

    // mark generating
    const markGenerating = deliverables.map((item, i) =>
      i === index ? { ...item, generating: true } : item
    );
    persistAndUpdateParent(markGenerating);

    try {
      const res = await fetch("/api/ai/sow", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          description: deliverable.description || deliverable.title,
          instruction,
        }),
      });
      const data = await res.json();
      if (data.addition) {
        const newDescription = deliverable.description.trim()
          ? deliverable.description.trim() + "\n\n" + data.addition.trim()
          : data.addition.trim();
        updateDeliverable(index, "description", newDescription);
        // mark generated
        const markGenerated = deliverables.map((item, i) =>
          i === index ? { ...item, generating: false, generated: true } : item
        );
        persistAndUpdateParent(markGenerated);
      } else {
        alert("AI did not return any improvement.");
        const unset = deliverables.map((item, i) =>
          i === index ? { ...item, generating: false } : item
        );
        persistAndUpdateParent(unset);
      }
    } catch (error) {
      console.error("Error improving SOW:", error);
      alert("Failed to improve the description.");
      const unset = deliverables.map((item, i) =>
        i === index ? { ...item, generating: false } : item
      );
      persistAndUpdateParent(unset);
    }
  };

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-semibold">🛠️ Scope of Work</h2>
      <p className="text-gray-600">Define clear deliverables for your procurement.</p>

      {deliverables.map((deliverable, index) => (
        <div key={index} className="border border-gray-200 rounded-lg p-4 space-y-2 bg-gray-50">
          <input
            type="text"
            placeholder="Deliverable Title"
            value={deliverable.title}
            onChange={(e) => updateDeliverable(index, "title", e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg"
          />
          <textarea
            placeholder="Deliverable Description"
            value={deliverable.description}
            onChange={(e) => updateDeliverable(index, "description", e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg"
            rows={4}
          />
          <input
            type="text"
            placeholder="Instruction for AI improvement"
            value={deliverable.userInstruction}
            onChange={(e) => updateDeliverable(index, "userInstruction", e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg"
          />

          <div className="flex items-center gap-3">
            <button
              onClick={() => handleGenerate(index)}
              className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition"
              disabled={deliverable.generating}
            >
              ✨ Improve with AI
            </button>

            {deliverable.generating ? (
              <span className="text-sm text-gray-600">Generating…</span>
            ) : deliverable.generated ? (
              <span className="text-sm text-green-600">Auto-generated</span>
            ) : (
              <span className="text-sm text-gray-500">Will auto-generate from title when available</span>
            )}
          </div>
        </div>
      ))}

      <button
        onClick={addDeliverable}
        className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition"
      >
        ➕ Add Deliverable
      </button>

      <div className="flex justify-between pt-4">
        <button onClick={prev} className="px-6 py-3 border border-gray-300 rounded-lg hover:bg-gray-50">
          ⬅ Back
        </button>
        <button onClick={next} className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
          Next ➜
        </button>
      </div>
    </div>
  );
}
